### PR TITLE
Feature/vs2022support

### PR DESCRIPTION
**Pull request by shuelsmeier**
Adds support for Visual Studio 2022 to the extension. Tested with Visual Studio 2022 Preview 7.0.

Fix for issue #17

### CODE REVIEW

**Comment by einaregilsson** [comment]
Thanks! I'll try to get this out today. Does the marketplace now allow having different versions of the same extension for VS2022 and then for VS2019 and older?

**Comment by einaregilsson** [comment]
Ok, I see that the Marketplace does not yet support having two vsix files, but they plan on supporting it. When they do I'll publish a new version. Thanks a lot for the contribution!

**Comment by shuelsmeier** [comment]
I just followed the official guide for upgrading visual studio extensions to 2022.

[Update a Visual Studio extension for Visual Studio 2022](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022)

> In the future, the Marketplace will allow you to upload multiple VSIXs to just one Marketplace listing, allowing you to upload your Visual Studio 2022-targeted VSIX and a pre-Visual Studio 2022 VSIX. Your users will automatically get the right VSIX for the VS version they have installed, when using the VS extension manager.

**Comment by daflotsch** [comment]
Thank you for the great extension! Is there any chance you can make the download for VS 2022 available somewhere here on GitHub in the meantime?

**Comment by einaregilsson** [comment]
@daflotsch I've actually set up GitHub actions now to build the extension on every commit. You can click on Actions and click on the latest workflow run and find a zip file under Artifacts with both the VS2019 and VS2022 versions. Here is a link to the latest version today: https://github.com/einaregilsson/StopOnFirstBuildError/suites/4256964033/artifacts/110539000

**Comment by lukasf** [comment]
What do you think about creating a second listing `StopOnFirstBuildError VS2022`? That is what almost all other extensions are doing, since the marketplace still does not support multiple VSIX per listing. The build artifact is expired and cannot be downloaded anymore.

**Pull request merged**
